### ISSUE TITLE
add more description for better learning

### ISSUE THREAD

**Issue by chiaz91** [TheMarvelousWhale/StudyWithSosig#1]
Can possibly add some explanations to following questions for people without background knowledge
- What is QPS?
- What is rate limiter? and what they do?
- Why rate limiter is needed?
- What's the difference between rate limiter and load balancer?
- Is rate limiter limits one device's queries or limit all general queries?
- How do we judge or choose right QPS? whate are necessary factors to consider?

**Comment by TheMarvelousWhale** [comment]
difference between rate limiter and load balancer:

rate limiter limit the rate of incoming traffic
load balance divides the incoming traffic to the servers that do the actual computing

both of these functionalities are often implemented together in an api gateway or reverse proxy
